[platformio]
default_envs = transmitter, receiver

[env]
monitor_speed = 115200

[env:transmitter]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<transmitter/>
  -<receiver/>
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306

[env:receiver]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<receiver/>
  -<transmitter/>

[env:native]
platform = native
test_framework = unity
