#ifndef S3_RUNTIME_CONFIG_H
#define S3_RUNTIME_CONFIG_H

#define S3_LVGL_DISPLAY_REFRESH_PERIOD_MS 16
#define S3_LVGL_INPUT_READ_PERIOD_MS 5
#define S3_LVGL_HANDLER_INTERVAL_MS 2
#define S3_MAIN_LOOP_DELAY_MS 2
#define S3_LVGL_DISPLAY_USE_DMA 1
#define S3_DISPLAY_FPS_SAMPLE_INTERVAL_MS 1000

#endif
