#ifndef S3_RUNTIME_CONFIG_H
#define S3_RUNTIME_CONFIG_H

#define S3_LVGL_DISPLAY_REFRESH_PERIOD_MS 16
#define S3_LVGL_INPUT_READ_PERIOD_MS 5
#define S3_LVGL_HANDLER_INTERVAL_MS 2
#define S3_MAIN_LOOP_DELAY_MS 2
#define S3_LVGL_DISPLAY_USE_DMA 1
#define S3_DISPLAY_FPS_SAMPLE_INTERVAL_MS 1000
#define S3_ESPNOW_STATUS_TIMEOUT_MS 1000
#define S3_ESPNOW_TX_POWER_DBM_X4 60
#define S3_ESPNOW_CONTROL_TASK_ENABLED 1
#define S3_ESPNOW_CONTROL_TASK_STACK_WORDS 4096
#define S3_ESPNOW_CONTROL_TASK_PRIORITY 3

#endif
